import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Header, Footer } from '@/components/shared';

export function generateStaticParams() { return [{ legal: 'privacidade' }, { legal: 'termos' }]; }
export default async function Legal({ params }: { params: Promise<{ legal: string }> }) {
  const { legal } = await params;
  if (!['privacidade', 'termos'].includes(legal)) notFound();
  return <><Header checkout /><main id="conteudo" className="legal-page container"><span className="eyebrow">FORMATURA DO BENJAMIM</span><h1>{legal === 'privacidade' ? 'Sua privacidade importa.' : 'Sobre esta campanha.'}</h1><p className="legal-intro">Texto inicial da prévia visual. As informações abaixo precisam ser revisadas e completadas antes da abertura das contribuições.</p>{legal === 'privacidade' ? <><h2>Dados nesta versão</h2><p>Os campos do checkout são apenas uma demonstração da interface. O site não envia nem armazena nome, CPF, WhatsApp ou e-mail. Não insira informações reais nesta prévia.</p><h2>Antes da publicação</h2><p>A família responsável deverá informar seu contato, a finalidade de cada dado solicitado, o prazo de retenção e o canal para acesso, correção ou exclusão. A coleta deve se limitar aos dados necessários.</p><h2>Pagamentos</h2><p>A integração prevista é com o Mercado Pago. Ela ainda não está ativa. O tratamento de dados pelo provedor e as condições aplicáveis deverão ser informados antes da ativação.</p></> : <><h2>Uma iniciativa da família</h2><p>Esta campanha é uma contribuição voluntária para a formatura do ABC do Benjamim. A escola não organiza a campanha e não é destinatária da arrecadação.</p><h2>Objetivo da arrecadação</h2><p>A meta bruta é de R$ 2.500: R$ 2.000 para a formatura, R$ 300 para despesas adicionais e uma reserva para taxas de pagamento. Contribuições não dão direito a prêmios ou participação em sorteios.</p><h2>Disponibilidade</h2><p>Esta versão apresenta apenas o visual do site. Não recebe pagamentos. Contato da família, condições de reembolso e destinação de eventual saldo excedente devem ser definidos antes do lançamento.</p></>}<Link className="button" href="/">Voltar à campanha</Link></main><Footer /></>;
}
